language: python
python: "3.6"
before_install:
  - openssl aes-256-cbc -K $encrypted_967435364d62_key -iv $encrypted_967435364d62_iv -in auth.tar.enc -out auth.tar -d
  - tar xvf auth.tar
install: python setup.py install
script: python setup.py test
sudo: false